### ISSUE TITLE
[BUG] 🅴🆁🆁🅾🆁 'episodeFile'

### ISSUE THREAD

**Issue by VegethB** [MainKronos/Sonarr-AnimeDownloader#131]
### Livello di Errore:
> _Selezionare solo un livello di errore_
- `🆆🅰🆁🅽🅸🅽🅶`
- `🅰🅻🅴🆁🆃`
x - `🅴🆁🆁🅾🆁`
- **`Other`**

### Messaggio di Errore
> _Insere qui il messaggio di errore._

<details>
 <description>errore:</decription>

2023-11-20 11:02:38 CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
2023-11-20 11:02:38 ERROR    'episodeFile'
2023-11-20 11:02:38 Traceback (most recent call last):
2023-11-20 11:02:38   File "/src/components/backend/core/Core.py", line 140, in run
2023-11-20 11:02:38     self.job()
2023-11-20 11:02:38   File "/src/components/backend/core/Core.py", line 171, in job
2023-11-20 11:02:38     self.downloader.download(serie)
2023-11-20 11:02:38   File "/src/components/backend/core/Downloader.py", line 121, in download
2023-11-20 11:02:38     self.__renameFile(episode['id'], serie['id'])
2023-11-20 11:02:38   File "/src/components/backend/core/Downloader.py", line 229, in __renameFile
2023-11-20 11:02:38     file_id = res.json()["episodeFile"]["id"]
2023-11-20 11:02:38 KeyError: 'episodeFile'
2023-11-20 11:02:39 
2023-11-20 11:02:39 
2023-11-20 11:02:39 -------------------------------------
2023-11-20 11:02:39 GID/UID
2023-11-20 11:02:39 -------------------------------------
2023-11-20 11:02:39 User uid:1000
2023-11-20 11:02:39 User gid:1000
2023-11-20 11:02:39 -------------------------------------
2023-11-20 11:02:39 
2023-11-20 11:02:39 
2023-11-20 11:02:57 INFO     ┌───────────────────────────────────[20 Nov 2023 11:02:57]───────────────────────────────────┐
2023-11-20 11:02:57 INFO     │                 _                _____                      _                 _            │
2023-11-20 11:02:57 INFO     │     /\         (_)              |  __ \                    | |               | |           │
2023-11-20 11:02:57 INFO     │    /  \   _ __  _ _ __ ___   ___| |  | | _____      ___ __ | | ___   __ _  __| | ___ _ __  │
2023-11-20 11:02:57 INFO     │   / /\ \ | '_ \| | '_ ` _ \ / _ \ |  | |/ _ \ \ /\ / / '_ \| |/ _ \ / _` |/ _` |/ _ \ '__| │
2023-11-20 11:02:57 INFO     │  / ____ \| | | | | | | | | |  __/ |__| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |    │
2023-11-20 11:02:38 Exception in thread Core:
2023-11-20 11:02:38 Traceback (most recent call last):
2023-11-20 11:02:38   File "/src/components/backend/core/Core.py", line 140, in run
2023-11-20 11:02:38     self.job()
2023-11-20 11:02:38   File "/src/components/backend/core/Core.py", line 171, in job
2023-11-20 11:02:38     self.downloader.download(serie)
2023-11-20 11:02:38   File "/src/components/backend/core/Downloader.py", line 121, in download
2023-11-20 11:02:38     self.__renameFile(episode['id'], serie['id'])
2023-11-20 11:02:38   File "/src/components/backend/core/Downloader.py", line 229, in __renameFile
2023-11-20 11:02:38     file_id = res.json()["episodeFile"]["id"]
2023-11-20 11:02:38 KeyError: 'episodeFile'
2023-11-20 11:02:38 
2023-11-20 11:02:38 During handling of the above exception, another exception occurred:
2023-11-20 11:02:38 
2023-11-20 11:02:38 Traceback (most recent call last):
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-11-20 11:02:38     self.run()
2023-11-20 11:02:38   File "/src/components/backend/core/Core.py", line 150, in run
2023-11-20 11:02:38     self.log.exception(e)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/logging/__init__.py", line 1481, in exception
2023-11-20 11:02:38     self.error(msg, *args, exc_info=exc_info, **kwargs)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
2023-11-20 11:02:38     self._log(ERROR, msg, args, **kwargs)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
2023-11-20 11:02:38     self.handle(record)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
2023-11-20 11:02:38     self.callHandlers(record)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
2023-11-20 11:02:38     hdlr.handle(record)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
2023-11-20 11:02:38     self.emit(record)
2023-11-20 11:02:38   File "/src/components/frontend/app.py", line 71, in emit
2023-11-20 11:02:38     socketio.emit("log", record.msg)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/site-packages/flask_socketio/__init__.py", line 462, in emit
2023-11-20 11:02:38     self.server.emit(event, *args, namespace=namespace, to=to,
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/site-packages/socketio/server.py", line 319, in emit
2023-11-20 11:02:38     self.manager.emit(event, data, namespace, room=room,
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/site-packages/socketio/base_manager.py", line 181, in emit
2023-11-20 11:02:38     encoded_packet = pkt.encode()
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/site-packages/socketio/packet.py", line 64, in encode
2023-11-20 11:02:38     encoded_packet += self.json.dumps(data, separators=(',', ':'))
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
2023-11-20 11:02:38     return cls(
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
2023-11-20 11:02:38     chunks = self.iterencode(o, _one_shot=True)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
2023-11-20 11:02:38     return _iterencode(o, 0)
2023-11-20 11:02:38   File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
2023-11-20 11:02:38     raise TypeError(f'Object of type {o.__class__.__name__} '
2023-11-20 11:02:38 TypeError: Object of type KeyError is not JSON serializable
2023-11-20 11:02:45 usermod: no changes
2023-11-20 11:02:57 INFO     │ /_/    \_\_| |_|_|_| |_| |_|\___|_____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|    │
2023-11-20 11:02:57 INFO     │                                                                                            │
2023-11-20 11:02:57 INFO     └───────────────────────────────────────────2.0.0────────────────────────────────────────────┘
2023-11-20 11:02:57 INFO     
2023-11-20 11:02:57 INFO     Globals
2023-11-20 11:02:57 INFO       ├── ctx.SONARR_URL = http://192.168.1.2:8989
2023-11-20 11:02:57 INFO       ├── ctx.API_KEY = :)
2023-11-20 11:02:57 DEBUG      ├── ctx.DOWNLOAD_FOLDER = /downloads
2023-11-20 11:02:57 DEBUG      ├── ctx.DATABASE_FOLDER = /src/database
2023-11-20 11:02:57 DEBUG      ├── ctx.SCRIPT_FOLDER = /src/script
2023-11-20 11:02:57 INFO       └── ctx.VERSION = 2.0.0
2023-11-20 11:02:57 INFO     
2023-11-20 11:02:57 INFO     Settings
2023-11-20 11:02:57 INFO       ├── TagsMode = WHITELIST
2023-11-20 11:02:57 INFO       ├── ScanDelay = 120
2023-11-20 11:02:57 INFO       ├── ScanDalay = 120
2023-11-20 11:02:57 INFO       ├── RenameEp = True
2023-11-20 11:02:57 INFO       ├── MoveEp = True
2023-11-20 11:02:57 INFO       ├── LogLevel = DEBUG
2023-11-20 11:02:57 INFO       └── AutoBind = True
2023-11-20 11:02:57 INFO     
2023-11-20 11:02:57 DEBUG    Tags
2023-11-20 11:02:57 DEBUG      └── 107 - aw-docker-download (🟢)
2023-11-20 11:48:50 Exception in thread Core:
2023-11-20 11:48:50 Traceback (most recent call last):
2023-11-20 11:48:50   File "/src/components/backend/core/Core.py", line 140, in run
2023-11-20 11:48:50     self.job()
2023-11-20 11:48:50   File "/src/components/backend/core/Core.py", line 171, in job
2023-11-20 11:48:50     self.downloader.download(serie)
2023-11-20 11:48:50   File "/src/components/backend/core/Downloader.py", line 121, in download
2023-11-20 11:48:50     self.__renameFile(episode['id'], serie['id'])
2023-11-20 11:48:50   File "/src/components/backend/core/Downloader.py", line 229, in __renameFile
2023-11-20 11:48:50     file_id = res.json()["episodeFile"]["id"]
2023-11-20 11:02:57 DEBUG    
2023-11-20 11:02:57 DEBUG    Connections
2023-11-20 11:02:57 DEBUG    
2023-11-20 11:02:57 INFO     
2023-11-20 11:02:57 INFO     ]────────────────────────────────────────────────────────────────────────────────────────────[
2023-11-20 11:02:57 INFO     
2023-11-20 11:02:57 INFO     ╭───────────────────────────────────「20 Nov 2023 11:02:57」───────────────────────────────────╮
2023-11-20 11:02:57 INFO     
2023-11-20 11:03:02 DEBUG    ❌ Serie 'Super Dragon Ball Heroes' scartata perchè non ha nessuno dei tag [aw-docker-download].
2023-11-20 11:03:02 INFO     
2023-11-20 11:03:02 INFO     ──────────────────────────────────────────────────────────────────────────────────────────────
2023-11-20 11:03:02 INFO     
2023-11-20 11:03:02 INFO     ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ 
2023-11-20 11:03:02 INFO     
2023-11-20 11:03:02 INFO     🔎 Ricerca serie 'The Seven Deadly Sins: Four Knights of the Apocalypse' stagione 1.
2023-11-20 11:03:02 INFO     🔎 Ricerca episodio 1, 2, 3, 4, 5, 6.
2023-11-20 11:03:03 INFO     
2023-11-20 11:03:03 INFO     ⚙️ Verifica se l'episodio S1E1 è disponibile.
2023-11-20 11:03:03 INFO     ✔️ L'episodio è disponibile.
2023-11-20 11:03:03 WARNING  ⏳ Download episodio S1E1.
2023-11-20 11:48:42 INFO     ✔️ Dowload Completato.
2023-11-20 11:48:42 WARNING  ⏳ Spostamento episodio episodio S1E1 in H:\Anime2\The Seven Deadly Sins - Four Knights of the Apocalypse.
2023-11-20 11:48:47 INFO     ✔️ Episodio spostato.
2023-11-20 11:48:47 INFO     ⏳ Aggiornamento serie 'The Seven Deadly Sins: Four Knights of the Apocalypse'.
2023-11-20 11:48:47 INFO     ⏳ Rinominando l'episodio.
2023-11-20 11:48:50 CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
2023-11-20 11:48:50 ERROR    'episodeFile'
2023-11-20 11:48:50 Traceback (most recent call last):
2023-11-20 11:48:50   File "/src/components/backend/core/Core.py", line 140, in run
2023-11-20 11:48:50     self.job()
2023-11-20 11:48:50   File "/src/components/backend/core/Core.py", line 171, in job
2023-11-20 11:48:50     self.downloader.download(serie)
2023-11-20 11:48:50   File "/src/components/backend/core/Downloader.py", line 121, in download
2023-11-20 11:48:50     self.__renameFile(episode['id'], serie['id'])
2023-11-20 11:48:50   File "/src/components/backend/core/Downloader.py", line 229, in __renameFile
2023-11-20 11:48:50     file_id = res.json()["episodeFile"]["id"]
2023-11-20 11:48:50 KeyError: 'episodeFile'
2023-11-20 11:48:50 KeyError: 'episodeFile'
2023-11-20 11:48:50 
2023-11-20 11:48:50 During handling of the above exception, another exception occurred:
2023-11-20 11:48:50 
2023-11-20 11:48:50 Traceback (most recent call last):
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-11-20 11:48:50     self.run()
2023-11-20 11:48:50   File "/src/components/backend/core/Core.py", line 150, in run
2023-11-20 11:48:50     self.log.exception(e)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/logging/__init__.py", line 1481, in exception
2023-11-20 11:48:50     self.error(msg, *args, exc_info=exc_info, **kwargs)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
2023-11-20 11:48:50     self._log(ERROR, msg, args, **kwargs)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
2023-11-20 11:48:50     self.handle(record)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
2023-11-20 11:48:50     self.callHandlers(record)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
2023-11-20 11:48:50     hdlr.handle(record)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
2023-11-20 11:48:50     self.emit(record)
2023-11-20 11:48:50   File "/src/components/frontend/app.py", line 71, in emit
2023-11-20 11:48:50     socketio.emit("log", record.msg)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/site-packages/flask_socketio/__init__.py", line 462, in emit
2023-11-20 11:48:50     self.server.emit(event, *args, namespace=namespace, to=to,
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/site-packages/socketio/server.py", line 319, in emit
2023-11-20 11:48:50     self.manager.emit(event, data, namespace, room=room,
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/site-packages/socketio/base_manager.py", line 181, in emit
2023-11-20 11:48:50     encoded_packet = pkt.encode()
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/site-packages/socketio/packet.py", line 64, in encode
2023-11-20 11:48:50     encoded_packet += self.json.dumps(data, separators=(',', ':'))
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
2023-11-20 11:48:50     return cls(
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
2023-11-20 11:48:50     chunks = self.iterencode(o, _one_shot=True)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
2023-11-20 11:48:50     return _iterencode(o, 0)
2023-11-20 11:48:50   File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
2023-11-20 11:48:50     raise TypeError(f'Object of type {o.__class__.__name__} '
2023-11-20 11:48:50 TypeError: Object of type KeyError is not JSON serializable
2023-11-20 11:48:52 usermod: no changes
2023-11-20 11:48:51 
2023-11-20 11:48:51 
2023-11-20 11:48:51 -------------------------------------
2023-11-20 11:48:51 GID/UID
2023-11-20 11:48:51 -------------------------------------
2023-11-20 11:48:51 User uid:1000
2023-11-20 11:48:51 User gid:1000
2023-11-20 11:48:51 -------------------------------------
2023-11-20 11:48:51 
2023-11-20 11:48:51 
2023-11-20 11:49:01 INFO     ┌───────────────────────────────────[20 Nov 2023 11:49:01]───────────────────────────────────┐
2023-11-20 11:49:01 INFO     │                 _                _____                      _                 _            │
2023-11-20 11:49:01 INFO     │     /\         (_)              |  __ \                    | |               | |           │
2023-11-20 11:49:01 INFO     │    /  \   _ __  _ _ __ ___   ___| |  | | _____      ___ __ | | ___   __ _  __| | ___ _ __  │
2023-11-20 11:49:01 INFO     │   / /\ \ | '_ \| | '_ ` _ \ / _ \ |  | |/ _ \ \ /\ / / '_ \| |/ _ \ / _` |/ _` |/ _ \ '__| │
2023-11-20 11:49:01 INFO     │  / ____ \| | | | | | | | | |  __/ |__| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |    │
2023-11-20 11:49:01 INFO     │ /_/    \_\_| |_|_|_| |_| |_|\___|_____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|    │
2023-11-20 11:49:01 INFO     │                                                                                            │
2023-11-20 11:49:01 INFO     └───────────────────────────────────────────2.0.0────────────────────────────────────────────┘
2023-11-20 11:49:01 INFO     

</details>

### Informazioni generali
> _Compilare i campi se correlato_
- **Nome Anime**: TUTTI
- **Stagione**: 
- **Episodio**: 
- **Link di AnimeWorld**: 

### Descrizione [_Opzionale_]
> _Inserire qui una breve descrizione del problema._

Problema presente fin da prima della 2.0.0 (ma non avevo proprio tempo per segnalare la questione).

Praticamente (da end user): 
Mi dice che trova un ep, va in download (eterno, 1 2 ore per 300mb di ep), poi quando sembra aver finito, va in erroe e riparte da 0 il download dello stesso episodio. Questa cosa va in loop.
~Inoltre, vedendo dal log di DEBUG, mi da che crea una cartella nuova invece che usare quella di Sonarr e NON rispetta le stagioni se l'ordine è assoluto sul json mentre sonarr suddivide a Season (One piece per esempio).~ Forse era colpa mia che avevo rimosso gli ep da sonarr (e sonarr deve aver cancellato anche le folder). Per One Piece, mi metteva gli ep nella folder principale invece che la season 21 (poi ha smesso). 

[DEBUG_2023-11-20-Docker.log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/13416593/DEBUG_2023-11-20-Docker.log)

**Comment by MainKronos** [comment]
mi puoi allegare anche il docker compose?

**Comment by MainKronos** [comment]
Il problema è il seguente:
- Il loop è dovuto all'errore critico; l'errore causa un arresto del container, ma essendo `unless-stopped` la politica di restart il container viene riavviato.
- L'errore è dovuto alla mancanza della chiave `episodeFile` nel dizionario che restituisce sonarr relativo alla richiesta di informazioni su un determinato episodio; questo dovrebbe essere causato dal fatto che Sonarr non ha ancora rilevato il file dell'episodio richiesto.

Dunque le possibili cause sono (dalla più probabile):
- Un errore nel parsing della directory di destinazione del file scaricato
- Lo spostamento dell'episodio impiega più di 2 secondi
- Problemi di rete

Quindi avrei bisogni della risposta a questa chiamata GET:
```
http://{IP}:{PORT}/api/v3/wanted/missing?includeSeries=true&apikey={API_KEY}
```
Dove `IP` e `PORT` sono l'ip e la porta di Sonarr e `API_KEY` è la chiave API di Sonarr.

**Comment by MainKronos** [comment]
Prova la versione `dev`, e vediamo se ho risolto il problema

**Comment by MainKronos** [comment]
Si, scusami, colpa mia. Sto riscrivendo il frontend usando una nuova libreria e ancora non l'avevo aggiunta al `requirements.txt`.
Riprova ora.

**Comment by MainKronos** [comment]
ma il file viene spostato in `H:\Anime2\The Seven Deadly Sins - Four Knights of the Apocalypse` ?

**Comment by MainKronos** [comment]
Dunque l'episodio non viene spostato. Ma la cartella esisteva di già prima del messaggio `La cartella H:\Anime2\The Seven Deadly Sins - Four Knights of the Apocalypse è stata creata.`?

Perchè a questo punto credo sia un problema di errore nel parsing della directory

**Comment by MainKronos** [comment]
Credo di essere riuscito a risolvere il problema. Infatti il problema era sul parsing della directory di destinazione del file 😅
Prova ad aggiornare l'immagine e vediamo se funziona

```sh
docker pull ghcr.io/mainkronos/anime_downloader:dev
```
