### ISSUE TITLE
[ISSUE] Container non parte CRITICAL 🅴🆁🆁🅾🆁

### ISSUE THREAD

**Issue by TheDestr0yer** [MainKronos/Sonarr-AnimeDownloader#134]
### Livello di Errore:
> _Selezionare solo un livello di errore_
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore

> 2024-01-16T10:54:28.790873174Z DEBUG      ├── ctx.SCRIPT_FOLDER = /src/script
2024-01-16T10:54:28.790925220Z INFO       └── ctx.VERSION = dev
2024-01-16T10:54:28.790981300Z INFO
2024-01-16T10:54:28.791035419Z INFO     Settings
2024-01-16T10:54:28.791100809Z INFO       ├── TagsMode = BLACKLIST
2024-01-16T10:54:28.791154506Z INFO       ├── AutoBind = True
2024-01-16T10:54:28.791213203Z INFO       ├── ScanDelay = 30
2024-01-16T10:54:28.791265157Z INFO       ├── MoveEp = True
2024-01-16T10:54:28.791322647Z INFO       ├── RenameEp = True
2024-01-16T10:54:28.791374415Z INFO       └── LogLevel = DEBUG
2024-01-16T10:54:28.791430471Z INFO
2024-01-16T10:54:28.791479345Z DEBUG    Tags
2024-01-16T10:54:28.791540793Z DEBUG
2024-01-16T10:54:28.791590036Z DEBUG    Connections
2024-01-16T10:54:28.791649267Z DEBUG
2024-01-16T10:54:28.822590514Z INFO
2024-01-16T10:54:28.822808303Z INFO     ]────────────────────────────────────────────────────────────────────────────────────────────[
2024-01-16T10:54:28.823014494Z INFO
2024-01-16T10:54:28.823052154Z INFO     ╭───────────────────────────────────「16 Jan 2024 11:54:28」───────────────────────────────────╮
2024-01-16T10:54:28.823192979Z INFO
2024-01-16T10:54:28.825605078Z CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
2024-01-16T10:54:28.829936289Z ERROR    Expecting value: line 1 column 1 (char 0)
2024-01-16T10:54:28.829957521Z Traceback (most recent call last):
2024-01-16T10:54:28.829962169Z   File "/src/components/backend/core/Core.py", line 144, in run
2024-01-16T10:54:28.829966069Z     self.job()
2024-01-16T10:54:28.829969722Z   File "/src/components/backend/core/Core.py", line 167, in job
2024-01-16T10:54:28.829973374Z     missing = self.processor.getData()
2024-01-16T10:54:28.829976914Z   File "/src/components/backend/core/Processor.py", line 24, in getData
2024-01-16T10:54:28.829980624Z     missing:Iterable = self.getAllMissing()
2024-01-16T10:54:28.829984191Z   File "/src/components/backend/core/Processor.py", line 53, in getAllMissing
2024-01-16T10:54:28.829987838Z     data = res.json()
2024-01-16T10:54:28.829991286Z   File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 762, in json
2024-01-16T10:54:28.829994929Z     return jsonlib.loads(self.content, **kwargs)
2024-01-16T10:54:28.829999117Z   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
2024-01-16T10:54:28.830005388Z     return _default_decoder.decode(s)
2024-01-16T10:54:28.830023148Z   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
2024-01-16T10:54:28.830027571Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-01-16T10:54:28.830031218Z   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
2024-01-16T10:54:28.830034829Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-01-16T10:54:28.830038442Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-01-16T10:54:28.913625806Z
2024-01-16T10:54:28.913678125Z
2024-01-16T10:54:28.913684251Z -------------------------------------
2024-01-16T10:54:28.913688430Z GID/UID
2024-01-16T10:54:28.913693013Z -------------------------------------
2024-01-16T10:54:28.913697211Z User uid:        1000
2024-01-16T10:54:28.913701360Z User gid:        1000
2024-01-16T10:54:28.913705285Z -------------------------------------
2024-01-16T10:54:28.913709019Z
2024-01-16T10:54:28.913713086Z

### Informazioni generali
> _Compilare i campi se correlato_
- **VERSIONE**: DEV
- **SISTEMA**: DOCKER SU UBUNTU

### Descrizione [_Opzionale_]
> _Funzionava fino a qualche giorno fa , ieri sera ho notato l'errore , stamattina ho provato anche ad aggiornare ma stesso problema._

**Comment by MainKronos** [comment]
Forse è un errore di Sonarr

Prova a riavviare Sonarr, controlla che l'URL e l'API Key di Sonarr siano corretti.
E poi riavvia il docker.

Se il problema non si risolve, dimmi cosa ti restituisce questo link:
```
http://{IP}:{PORT}/api/v3/wanted/missing?includeSeries=true&apikey={API_KEY}
```

**Comment by TheDestr0yer** [comment]
> Forse è un errore di Sonarr
> 
> Prova a riavviare Sonarr, controlla che l'URL e l'API Key di Sonarr siano corretti. E poi riavvia il docker.
> 
> Se il problema non si risolve, dimmi cosa ti restituisce questo link:
> 
> ```
> http://{IP}:{PORT}/api/v3/wanted/missing?includeSeries=true&apikey={API_KEY}
> ```

Ho riavviato più volte , ho provato anche a cancellare e reinstallare il container ma niente , il link mi riporta questo
`{
  "page": 1,
  "pageSize": 10,
  "sortKey": "Episodes.Id",
  "sortDirection": "descending",
  "totalRecords": 0,
  "records": []
}`

**Comment by MainKronos** [comment]
probabilmente è il `SONARR_URL` che hai inserito nel docker file. Se termina con uno `/` è quello il problema, prova a rimuoverlo.

**Comment by MainKronos** [comment]
l'errore è sempre presente?
Che versione di Sonarr usi?

**Comment by TheDestr0yer** [comment]
Ciao , si dopo aver cancellato bene tutto e reinstallato il container è ripartito , sempre la versione dev , non so perchè mi diede quell'errore.

**Comment by bubez81** [comment]
Buonasera, riapro questo post perchè improvvisamente oggi, accade questo:

```
ERROR    Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/src/components/backend/core/Core.py", line 144, in run
    self.job()
  File "/src/components/backend/core/Core.py", line 167, in job
    missing = self.processor.getData()
  File "/src/components/backend/core/Processor.py", line 36, in getData
    missing = list(map(self.__sortSerie, missing))
  File "/src/components/backend/core/Processor.py", line 272, in __bindUrl
    elem["seasons"] = list(filter(filterSeason, elem["seasons"]))
  File "/src/components/backend/core/Processor.py", line 248, in filterSeason
    res = self.external.find(title, season["number"], elem["tvdbId"])
  File "/src/components/backend/connection/ExternalDB.py", line 68, in find
    res = aw.find(title)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 54, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 49, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 116, in find
    data = res.json()
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
-------------------------------------
```

facendo qualche esperimento avviene se animedownloader matcha con un tag esistente su sonarr, senza tag configurati non avviene
