### ISSUE TITLE
[ERROR] Critical Error quando avvio il container

### ISSUE THREAD

**Issue by TheDestr0yer** [MainKronos/Sonarr-AnimeDownloader#136]
Salve , ho sempre usato questo docker su ubuntu ma per esigenze ho dovuto installarlo anche su Windows 10 (sempre docker) ,  quando avvio il container pero ottengo il seguente errore , ci tengo a specificare che se faccio partire il container senza nessuna serie da cerca lui va normalmente : 
```2024-02-09 12:41:57 INFO     ┌───────────────────────────────────[09 Feb 2024 12:41:57]───────────────────────────────────┐
2024-02-09 12:41:57 INFO     │                 _                _____                      _                 _            │
2024-02-09 12:41:57 INFO     │     /\         (_)              |  __ \                    | |               | |           │
2024-02-09 12:41:57 INFO     │    /  \   _ __  _ _ __ ___   ___| |  | | _____      ___ __ | | ___   __ _  __| | ___ _ __  │
2024-02-09 12:41:57 INFO     │   / /\ \ | '_ \| | '_ ` _ \ / _ \ |  | |/ _ \ \ /\ / / '_ \| |/ _ \ / _` |/ _` |/ _ \ '__| │
2024-02-09 12:41:57 INFO     │  / ____ \| | | | | | | | | |  __/ |__| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |    │
2024-02-09 12:41:57 INFO     │ /_/    \_\_| |_|_|_| |_| |_|\___|_____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|    │
2024-02-09 12:41:57 INFO     │                                                                                            │
2024-02-09 12:41:57 INFO     └────────────────────────────────────────────dev─────────────────────────────────────────────┘
2024-02-09 12:41:57 INFO     
2024-02-09 12:41:57 INFO     Globals
2024-02-09 12:41:57 INFO       ├── ctx.SONARR_URL = http://192.168.1.4:8989
2024-02-09 12:41:57 INFO       ├── ctx.API_KEY = xxxxxx
2024-02-09 12:41:57 DEBUG      ├── ctx.DOWNLOAD_FOLDER = /downloads
2024-02-09 12:41:57 DEBUG      ├── ctx.DATABASE_FOLDER = /src/database
2024-02-09 12:41:57 DEBUG      ├── ctx.SCRIPT_FOLDER = /src/script
2024-02-09 12:41:57 INFO       └── ctx.VERSION = dev
2024-02-09 12:41:57 INFO     
2024-02-09 12:41:57 INFO     Settings
2024-02-09 12:41:57 INFO       ├── TagsMode = BLACKLIST
2024-02-09 12:41:57 INFO       ├── ScanDelay = 30
2024-02-09 12:41:57 INFO       ├── AutoBind = True
2024-02-09 12:41:57 INFO       ├── RenameEp = True
2024-02-09 12:41:57 INFO       ├── MoveEp = True
2024-02-09 12:41:57 INFO       └── LogLevel = DEBUG
2024-02-09 12:41:57 INFO     
2024-02-09 12:41:57 DEBUG    Tags
2024-02-09 12:41:57 DEBUG    
2024-02-09 12:41:57 DEBUG    Connections
2024-02-09 12:41:57 DEBUG    
2024-02-09 12:41:57 INFO     
2024-02-09 12:41:57 INFO     ]────────────────────────────────────────────────────────────────────────────────────────────[
2024-02-09 12:41:57 INFO     
2024-02-09 12:41:57 INFO     ╭───────────────────────────────────「09 Feb 2024 12:41:57」───────────────────────────────────╮
2024-02-09 12:41:57 INFO     
2024-02-09 12:41:57 DEBUG    ❌ Stagione 1 della serie 'Parasyte: The Maxim' non è presente nella TABELLA DI CONVERSIONE.
2024-02-09 12:41:58 CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
2024-02-09 12:41:58 ERROR    'sceneSeasonNumber'
2024-02-09 12:41:58 Traceback (most recent call last):
2024-02-09 12:41:58   File "/src/components/backend/core/Core.py", line 144, in run
2024-02-09 12:41:58     self.job()
2024-02-09 12:41:58   File "/src/components/backend/core/Core.py", line 167, in job
2024-02-09 12:41:58     missing = self.processor.getData()
2024-02-09 12:41:58   File "/src/components/backend/core/Processor.py", line 36, in getData
2024-02-09 12:41:58     missing = list(map(self.__sortSerie, missing))
2024-02-09 12:41:58   File "/src/components/backend/core/Processor.py", line 264, in __bindUrl
2024-02-09 12:41:58     elem["seasons"] = list(filter(filterSeason, elem["seasons"]))
2024-02-09 12:41:58   File "/src/components/backend/core/Processor.py", line 243, in filterSeason
2024-02-09 12:41:58     alt_titles = getAlternativeTitles(elem['id'],season_number)
2024-02-09 12:41:58   File "/src/components/backend/core/Processor.py", line 205, in getAlternativeTitles
2024-02-09 12:41:58     return [
2024-02-09 12:41:58   File "/src/components/backend/core/Processor.py", line 208, in <listcomp>
2024-02-09 12:41:58     if x["sceneSeasonNumber"] == -1 or x["sceneSeasonNumber"] == season_number
2024-02-09 12:41:58 KeyError: 'sceneSeasonNumber'
2024-02-09 12:41:58 
2024-02-09 12:41:58 
2024-02-09 12:41:58 -------------------------------------
2024-02-09 12:41:58 GID/UID
2024-02-09 12:41:58 -------------------------------------
2024-02-09 12:41:58 User uid:   1000
2024-02-09 12:41:58 User gid:   1000
2024-02-09 12:41:58 -------------------------------------
2024-02-09 12:41:58 
2024-02-09 12:41:58
```
il comando usato per installare il tutto è il seguente : 
```
docker run -d `                                                                                  
>>     --name AnimeDownloader `                                                                                         
>>     -v D:\Plex\Config\AnimeD\data\database:/src/database `                                                           
>>     -v D:\Plex\Anime:/tv `                                                                                           
>>     -v D:\Plex\Config\AnimeD\download:/downloads `                                                                   
>>     -v D:\Plex\Config\AnimeD\data\script:/src/script `                                                               
>>     -p 5000:5000 `                                                                                                   
>>     -e SONARR_URL=http://192.168.1.4:8989 `                                                                          
>>     -e API_KEY=xxxxx `                                                                                     
>>     -e TZ=Europe/Rome `                                                                                              
>>     -e PUID=1000 `                                                                                                   
>>     -e PGID=1000 `                                                                                                   
>>     ghcr.io/mainkronos/anime_downloader:dev  
``` 
Dall URL `http://{IP}:{PORT}/api/v3/wanted/missing?includeSeries=true&apikey={API_KEY}` ottengo questo risultato : 
https://pastebin.com/raw/tKMnSpq4

**Comment by MainKronos** [comment]
È Sicuramente dovuto all'ultimo aggiornamento #113 
Mi puoi dire cosa ottieni da questo: 
```
http://{IP}:{PORT}/api/v3/series&apikey={API_KEY}
```

**Comment by TheDestr0yer** [comment]
> È Sicuramente dovuto all'ultimo aggiornamento #113 Mi puoi dire cosa ottieni da questo:
> 
> ```
> http://{IP}:{PORT}/api/v3/series&apikey={API_KEY}
> ```

Ho provato ma non mi carica la pagina

**Comment by MainKronos** [comment]
Scusami ho scritto male 😂
```
http://{IP}:{PORT}/api/v3/series?apikey={API_KEY}
```

**Comment by TheDestr0yer** [comment]
Ah ok 😂 . Ecco qui 
[text.txt](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/14224664/text.txt)

**Comment by MainKronos** [comment]
Dovrei aver risolto nella versione dev

**Comment by TheDestr0yer** [comment]
> Dovrei aver risolto nella versione dev

Adesso funziona , grandissimo come sempre.

**Comment by TheDestr0yer** [comment]
> Dovrei aver risolto nella versione dev

Avevo lasciato gli episodi a scaricare ma al ritorno ho notato questo errore , i permessi li ho controllati e sono tutti ok.

```
024-02-09 20:56:18 INFO     ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ 
2024-02-09 20:56:18 INFO     
2024-02-09 20:56:18 INFO     🔎 Ricerca serie 'Parasyte: The Maxim' stagione 1.
2024-02-09 20:56:18 INFO     🔎 Ricerca episodio 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24.
2024-02-09 20:56:18 INFO     
2024-02-09 20:56:18 INFO     ⚙️ Verifica se l'episodio S1E1 è disponibile.
2024-02-09 20:56:18 INFO     ✔️ L'episodio è disponibile.
2024-02-09 20:56:18 WARNING  ⏳ Download episodio S1E1.
2024-02-09 20:59:46 INFO     ✔️ Dowload Completato.
2024-02-09 20:59:46 WARNING  ⏳ Spostamento episodio episodio S1E1 in D:\Plex\Anime\Parasyte - The Maxim (2014).
2024-02-09 20:59:46 CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
2024-02-09 20:59:46 ERROR    [Errno 13] Permission denied: '/Plex'
2024-02-09 20:59:46 Traceback (most recent call last):
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1313, in mkdir
2024-02-09 20:59:46     self._accessor.mkdir(self, mode)
2024-02-09 20:59:46 FileNotFoundError: [Errno 2] No such file or directory: '/Plex/Anime/Parasyte - The Maxim (2014)'
2024-02-09 20:59:46 
2024-02-09 20:59:46 During handling of the above exception, another exception occurred:
2024-02-09 20:59:46 
2024-02-09 20:59:46 Traceback (most recent call last):
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1313, in mkdir
2024-02-09 20:59:46     self._accessor.mkdir(self, mode)
2024-02-09 20:59:46 FileNotFoundError: [Errno 2] No such file or directory: '/Plex/Anime'
2024-02-09 20:59:46 
2024-02-09 20:59:46 During handling of the above exception, another exception occurred:
2024-02-09 20:59:46 
2024-02-09 20:59:46 Traceback (most recent call last):
2024-02-09 20:59:46   File "/src/components/backend/core/Core.py", line 144, in run
2024-02-09 20:59:46     self.job()
2024-02-09 20:59:46   File "/src/components/backend/core/Core.py", line 177, in job
2024-02-09 20:59:46     self.downloader.download(serie)
2024-02-09 20:59:46   File "/src/components/backend/core/Downloader.py", line 104, in download
2024-02-09 20:59:46     if not self.__moveFile(file, destination):
2024-02-09 20:59:46   File "/src/components/backend/core/Downloader.py", line 211, in __moveFile
2024-02-09 20:59:46     dst.mkdir(parents=True)
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1317, in mkdir
2024-02-09 20:59:46     self.parent.mkdir(parents=True, exist_ok=True)
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1317, in mkdir
2024-02-09 20:59:46     self.parent.mkdir(parents=True, exist_ok=True)
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1313, in mkdir
2024-02-09 20:59:46     self._accessor.mkdir(self, mode)
2024-02-09 20:59:46 PermissionError: [Errno 13] Permission denied: '/Plex'
2024-02-09 20:59:46 
2024-02-09 20:59:46 
2024-02-09 20:59:46 -------------------------------------
2024-02-09 20:59:46 GID/UID
2024-02-09 20:59:46 -------------------------------------
2024-02-09 20:59:46 User uid:   1000
2024-02-09 20:59:46 User gid:   1000
2024-02-09 20:59:46 -------------------------------------
2024-02-09 20:59:46 
2024-02-09 20:59:46 
```
