### ISSUE TITLE
[HELP] [Errno 13] Permission denied

### ISSUE THREAD

**Issue by MainKronos** [MainKronos/Sonarr-AnimeDownloader#138]
> Dovrei aver risolto nella versione dev

Avevo lasciato gli episodi a scaricare ma al ritorno ho notato questo errore , i permessi li ho controllati e sono tutti ok. il file viene scaricato nella cartella download impostata ma non riesce a spostarlo. Ho provato anche a creare cartelle ed eliminare file dal bash del container e me lo fa fare.

```
024-02-09 20:56:18 INFO     ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ 
2024-02-09 20:56:18 INFO     
2024-02-09 20:56:18 INFO     🔎 Ricerca serie 'Parasyte: The Maxim' stagione 1.
2024-02-09 20:56:18 INFO     🔎 Ricerca episodio 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24.
2024-02-09 20:56:18 INFO     
2024-02-09 20:56:18 INFO     ⚙️ Verifica se l'episodio S1E1 è disponibile.
2024-02-09 20:56:18 INFO     ✔️ L'episodio è disponibile.
2024-02-09 20:56:18 WARNING  ⏳ Download episodio S1E1.
2024-02-09 20:59:46 INFO     ✔️ Dowload Completato.
2024-02-09 20:59:46 WARNING  ⏳ Spostamento episodio episodio S1E1 in D:\Plex\Anime\Parasyte - The Maxim (2014).
2024-02-09 20:59:46 CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
2024-02-09 20:59:46 ERROR    [Errno 13] Permission denied: '/Plex'
2024-02-09 20:59:46 Traceback (most recent call last):
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1313, in mkdir
2024-02-09 20:59:46     self._accessor.mkdir(self, mode)
2024-02-09 20:59:46 FileNotFoundError: [Errno 2] No such file or directory: '/Plex/Anime/Parasyte - The Maxim (2014)'
2024-02-09 20:59:46 
2024-02-09 20:59:46 During handling of the above exception, another exception occurred:
2024-02-09 20:59:46 
2024-02-09 20:59:46 Traceback (most recent call last):
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1313, in mkdir
2024-02-09 20:59:46     self._accessor.mkdir(self, mode)
2024-02-09 20:59:46 FileNotFoundError: [Errno 2] No such file or directory: '/Plex/Anime'
2024-02-09 20:59:46 
2024-02-09 20:59:46 During handling of the above exception, another exception occurred:
2024-02-09 20:59:46 
2024-02-09 20:59:46 Traceback (most recent call last):
2024-02-09 20:59:46   File "/src/components/backend/core/Core.py", line 144, in run
2024-02-09 20:59:46     self.job()
2024-02-09 20:59:46   File "/src/components/backend/core/Core.py", line 177, in job
2024-02-09 20:59:46     self.downloader.download(serie)
2024-02-09 20:59:46   File "/src/components/backend/core/Downloader.py", line 104, in download
2024-02-09 20:59:46     if not self.__moveFile(file, destination):
2024-02-09 20:59:46   File "/src/components/backend/core/Downloader.py", line 211, in __moveFile
2024-02-09 20:59:46     dst.mkdir(parents=True)
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1317, in mkdir
2024-02-09 20:59:46     self.parent.mkdir(parents=True, exist_ok=True)
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1317, in mkdir
2024-02-09 20:59:46     self.parent.mkdir(parents=True, exist_ok=True)
2024-02-09 20:59:46   File "/usr/local/lib/python3.9/pathlib.py", line 1313, in mkdir
2024-02-09 20:59:46     self._accessor.mkdir(self, mode)
2024-02-09 20:59:46 PermissionError: [Errno 13] Permission denied: '/Plex'
2024-02-09 20:59:46 
2024-02-09 20:59:46 
2024-02-09 20:59:46 -------------------------------------
2024-02-09 20:59:46 GID/UID
2024-02-09 20:59:46 -------------------------------------
2024-02-09 20:59:46 User uid:   1000
2024-02-09 20:59:46 User gid:   1000
2024-02-09 20:59:46 -------------------------------------
2024-02-09 20:59:46 
2024-02-09 20:59:46 
```

_Originally posted by @TheDestr0yer in https://github.com/MainKronos/Sonarr-AnimeDownloader/issues/136#issuecomment-1936538064_

**Comment by MainKronos** [comment]
Che permessi ha la cartella `/Plex` ?

**Comment by MainKronos** [comment]
Mi puoi scrivere anche la configurazione che hai usato per sonarr? Forse è li il problema

**Comment by TheDestr0yer** [comment]
> Mi puoi scrivere anche la configurazione che hai usato per sonarr? Forse è li il problema

Questo sonarr è installato direttamente su Windows, non ho usato docker.

**Comment by MainKronos** [comment]
ok, allora apri la web page di Sonarr -> Settings -> Media management -> Root Folders 

```
http://{IP}:{PORT}/settings/mediamanagement
``` 

Scrivimi cosa ti appare

**Comment by TheDestr0yer** [comment]
> ok, allora apri la web page di Sonarr -> Settings -> Media management -> Root Folders
> 
> ```
> http://{IP}:{PORT}/settings/mediamanagement
> ```
> 
> Scrivimi cosa ti appare

Mi appare la Root Folders che ti ho detto prima,
![Cattura](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/53081713/7b219133-c80e-4c4b-934b-22a98faaac22)

Potrebbe essere un problema di incompatibilità dello script ad istanze di sonarr direttamente su Windows  ?

**Comment by MainKronos** [comment]
Probabilmente è simile a questo [problema](https://mainkronos.github.io/Sonarr-AnimeDownloader/usage/faq/#uso-sonarr-ma-non-con-docker-e-non-so-quale-mount-dovrei-fare) e a [questo](https://mainkronos.github.io/Sonarr-AnimeDownloader/usage/faq/#uso-sonarr-in-ambiente-windows-come-devo-fare-il-mount)


Quindi prova a modificare lo script in questo:

```cmd
docker run -d `                                                                                  
     --name AnimeDownloader `
     -v D:\Plex\Config\AnimeD\data\database:/src/database `
     -v D:\Plex\Anime:/Plex/Anime `
     -v D:\Plex\Config\AnimeD\download:/downloads `
     -v D:\Plex\Config\AnimeD\data\script:/src/script `
     -p 5000:5000 `
     -e SONARR_URL=http://192.168.1.4:8989 `
     -e API_KEY=xxxxxxxxxx `
     -e TZ=Europe/Rome `
     ghcr.io/mainkronos/anime_downloader:dev
```

**Comment by TheDestr0yer** [comment]
Il problema sembrerebbe essersi risolto impostando il mount come hai detto tu `-v D:\Plex\Anime:/Plex/Anime` per adesso ho scaricato due episodi e mi ha creato la cartella e spostato gli episodi senza problemi
