### ISSUE TITLE
[BUG] Episodio non trovato

### ISSUE THREAD

**Issue by geenopippo** [MainKronos/Sonarr-AnimeDownloader#146]
Salve di nuovo, dopo essere riuscito a settare il docker correttamente, ora salta fuori questo errore:
> _Selezionare solo un livello di errore_
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
INFO     ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ 
INFO     
INFO     🔎 Ricerca serie 'Mirai Nikki' stagione absolute.
INFO     🔎 Ricerca episodio 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26.
INFO     
INFO     ⚙️ Verifica se l'episodio S1E1 è disponibile.
INFO     ✔️ L'episodio è disponibile.
WARNING  ⏳ Download episodio S1E1.
INFO     ✔️ Dowload Completato.
WARNING  ⏳ Spostamento episodio episodio S1E1 in /downloads/Mirai Nikki.
WARNING  ⚠️ La cartella /downloads/Mirai Nikki è stata creata.
INFO     ✔️ Episodio spostato.
INFO     ⏳ Aggiornamento serie 'Mirai Nikki'.
INFO     ⏳ Rinominando l'episodio.
CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
ERROR    Episodio Non trovato
Traceback (most recent call last):
  File "/src/components/backend/core/Core.py", line 144, in run
    self.job()
  File "/src/components/backend/core/Core.py", line 177, in job
    self.downloader.download(serie)
  File "/src/components/backend/core/Downloader.py", line 121, in download
    self.__renameFile(episode['id'], serie['id'])
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/src/components/backend/core/Downloader.py", line 231, in __renameFile
    if "episodeFile" not in res: raise Exception("Episodio Non trovato")
Exception: Episodio Non trovato

**Comment by MainKronos** [comment]
Probabilmente hai collegato male la directory in cui vanno a finire gli episodi scaricati, dai un occhiata [qui](https://mainkronos.github.io/Sonarr-AnimeDownloader/usage/quickstart/#volume-tv) forse c'è la soluzione al tuo problema

**Comment by geenopippo** [comment]
![image](https://github.com/user-attachments/assets/27d6f6f5-8010-4c68-b4d1-64048f0ed563)
Questo è il path di Sonarr

![image](https://github.com/user-attachments/assets/4ca15dbe-8a73-472d-a502-17339767d8a8)
E questo di AnimeDownloader

Non vedo errori apparenti, oppure sono io ad aver sbagliato qualcosa?

**Comment by geenopippo** [comment]
UPDATE: Ha iniziato a scaricare degli episodi, ma poi si è fermato. Ecco il LOG:

INFO     ⚙️ Verifica se l'episodio S1E6 è disponibile.
INFO     ✔️ L'episodio è disponibile.
WARNING  ⏳ Download episodio S1E6.
INFO     ✔️ Dowload Completato.
WARNING  ⏳ Spostamento episodio episodio S1E6 in /downloads/Mirai Nikki.
INFO     ✔️ Episodio spostato.
INFO     ⏳ Aggiornamento serie 'Mirai Nikki'.
INFO     ⏳ Rinominando l'episodio.
CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
ERROR    Episodio Non trovato
Traceback (most recent call last):
  File "/src/components/backend/core/Core.py", line 144, in run
    self.job()
  File "/src/components/backend/core/Core.py", line 177, in job
    self.downloader.download(serie)
  File "/src/components/backend/core/Downloader.py", line 121, in download
    self.__renameFile(episode['id'], serie['id'])
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/src/components/backend/core/Downloader.py", line 231, in __renameFile
    if "episodeFile" not in res: raise Exception("Episodio Non trovato")
Exception: Episodio Non trovato


-------------------------------------
GID/UID
-------------------------------------
User uid:       0
User gid:       0
-------------------------------------



Se riavvio il container poi riprende il download, ad una velocità fissa di 1.46 MB/s.

**Comment by MainKronos** [comment]
Credo che il tuo problema sia simile a [questo](https://github.com/MainKronos/Sonarr-AnimeDownloader/issues/101), prova a darci un'occhiata
