### ISSUE TITLE
Rinominazione episodi secondo schema Sonarr

### ISSUE THREAD

**Issue by EffeF** [MainKronos/Sonarr-AnimeDownloader#19]
È possibile avere una rinominazione degli episodi che segua quello impostato su Sonarr?

Ad esempio, per `My Hero Academia`, l'episodio scaricato sarà:
`My Hero Academia - S3E25.mp4`
mentre per Sonarr, secondo lo schema impostato:
`{Series Title} - S{season:00}E{episode:00} ({absolute:000}) - {Episode Title}`,
dovrebbe essere:
`Season 3/My Hero Academia - S03E25 (063) - Unrivaled.mp4`

Se fattibile, migliorerebbe ulteriormente l'automatizzazione evitando di dover ricorrere alla funzione di rinominazione di Sonarr

![Screenshot_2021-03-18 My Hero Academia - Sonarr](https://user-images.githubusercontent.com/25557983/111660198-21a03800-880e-11eb-969b-0f5eaa6e3abc.png)

**Comment by MainKronos** [comment]
mhhh, strano.... dovrebbe già farlo😅
poi inviare i log di quando li scarica?

**Comment by EffeF** [comment]
Ecco: [_anime_logs.txt](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/6166366/_anime_logs.txt)

Tra l'altro con gli episodi scaricati con questo script non funziona neanche la rinominazione di Sonarr, mi da il seguente errore nel log di Sonarr:
```log
21-3-18 18:51:06.8|Error|RenameEpisodeFileService|Failed to rename file xxxxxxxxxxx/My Hero Academia/My Hero Academia - S3E24.mp4

[v3.0.5.1144] System.UnauthorizedAccessException: Access to the path "xxxxxxxxxxx/My Hero Academia/Season 3" is denied.
```

**Comment by MainKronos** [comment]
mhhhh... ti faccio una raffica di domande per capire meglio....😅
- la cartella `xxxxxxxxxxx/My Hero Academia` esisteva prima di scaricare gli episodi?
- la cartella `xxxxxxxxxxx/My Hero Academia/Season 3` esisteva prima di scaricare gli episodi?
- se hai usato docker per sonarr, quali valori hai messo per le variabili d'ambiente `PUID` e `PGID`?
- quali sono i permessi di lettura e scrittura della cartella `xxxxxxxxxxx/My Hero Academia`?
- quali sono i permessi di lettura e scrittura del file `xxxxxxxxxxx/My Hero Academia/My Hero Academia - S3E24.mp4`?

**Comment by EffeF** [comment]
- la cartella `xxxxxxxxxxx/My Hero Academia` esisteva prima di scaricare gli episodi?
No, è stata creata dallo script

- la cartella `xxxxxxxxxxx/My Hero Academia/Season 3` esisteva prima di scaricare gli episodi?
No, e non esiste tuttora

- se hai usato docker per sonarr, quali valori hai messo per le variabili d'ambiente `PUID` e `PGID`?
1000/1000

- quali sono i permessi di lettura e scrittura della cartella `xxxxxxxxxxx/My Hero Academia`?
drwxr-xr-x (755)

- quali sono i permessi di lettura e scrittura del file `xxxxxxxxxxx/My Hero Academia/My Hero Academia - S3E24.mp4`?
-rw-r--r-- (644)

**Comment by MainKronos** [comment]
prova a mettere questo settaggio:
```
docker run -d \
    --name=AnimeDownloader \
    -v /path/to/data:/script/json/ \
    -v /path/to/animeSeries:/tv \
    -p {port}:5000 \
    -u 1000:1000 \    <----------------------------------------------------------- aggiungi questo qui
    --env SONARR_URL='http://{url}:{port}' \
    --env API_KEY='1234567890abcdefghijklmn' \
    --env CHAT_ID=123456789 \
    --env BOT_TOKEN='123456789:ABCDEFGHIJKLM-abc_AbCdEfGhI12345678' \
    --env TZ=Europe/Rome \
    mainkronos/anime_downloader
```

Dimmi se poi ci sono errori di permessi che proviamo poi a risolverli 👍

**Comment by EffeF** [comment]
```log
┌------------------------------------18 Mar 2021 22:44:26------------------------------------┐
|                 _                _____                      _                 _            |
|     /\         (_)              |  __ \                    | |               | |           |
|    /  \   _ __  _ _ __ ___   ___| |  | | _____      ___ __ | | ___   __ _  __| | ___ _ __  |
|   / /\ \ | '_ \| | '_ ` _ \ / _ \ |  | |/ _ \ \ /\ / / '_ \| |/ _ \ / _` |/ _` |/ _ \ '__| |
|  / ____ \| | | | | | | | | |  __/ |__| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |    |
| /_/    \_\_| |_|_|_| |_| |_|\___|_____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|    |
|                                                                                            |
└--------------------------------------------------------------------------------------------┘

✔ 𝙎𝙊𝙉𝘼𝙍𝙍_𝙐𝙍𝙇: http://192.168.1.100:8989/sonarr/
✔ 𝘼𝙋𝙄_𝙆𝙀𝙔: xxxxxxxxxxx
✖️ Variabile d'ambinete '𝘾𝙃𝘼𝙏_𝙄𝘿' non inserita.
✖️ Variabile d'ambinete '𝘽𝙊𝙏_𝙏𝙊𝙆𝙀𝙉' non inserita.
☑️ Le variabili d'ambiente sono state inserite correttamente.
⚙️ Intervallo Scan: 30 minuti
AVVIO SERVER
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
╭-----------------------------------「18 Mar 2021 22:44:27」-----------------------------------╮
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
🔎 Ricerca anime 'My Hero Academia' per l'episodio S3E25.
🔎 Ricerca degli episodi per 'My Hero Academia'.
⚙️ Verifica se l'episodio 𝐒3𝐄25 è disponibile.
✔️ L'episodio è disponibile.
⏳ Download episodio 𝐒3𝐄25.
🅴🆁🆁🅾🆁: [Errno 13] Permission denied: 'My Hero Academia - S3E25.mp4'
Traceback (most recent call last):
  File "/script/main.py", line 125, in job
    if fileLink.download(title):
  File "/usr/local/lib/python3.6/dist-packages/animeworld/__init__.py", line 234, in download
    return self._downloadIn(title)
  File "/usr/local/lib/python3.6/dist-packages/animeworld/__init__.py", line 183, in _downloadIn
    with open(f"{title}.mp4", 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'My Hero Academia - S3E25.mp4'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
╰-----------------------------------「18 Mar 2021 23:14:35」-----------------------------------╯
```

**Comment by MainKronos** [comment]
2 opzioni:
- metodo facile: 
  - cancelli il volume associato a `/path/to/data:/script/json/` e lo ricrei
- metodo poco meno facile: 
  - esegui `chmod -R 777 /script/` all'interno del container

**Comment by EffeF** [comment]
Ok, con il "metodo facile" non ha funzionato, ma con l'altro si, e adesso lo rinomina correttamente.

```log
┌------------------------------------18 Mar 2021 23:26:02------------------------------------┐
|                 _                _____                      _                 _            |
|     /\         (_)              |  __ \                    | |               | |           |
|    /  \   _ __  _ _ __ ___   ___| |  | | _____      ___ __ | | ___   __ _  __| | ___ _ __  |
|   / /\ \ | '_ \| | '_ ` _ \ / _ \ |  | |/ _ \ \ /\ / / '_ \| |/ _ \ / _` |/ _` |/ _ \ '__| |
|  / ____ \| | | | | | | | | |  __/ |__| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |    |
| /_/    \_\_| |_|_|_| |_| |_|\___|_____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|    |
|                                                                                            |
└--------------------------------------------------------------------------------------------┘
✔ 𝙎𝙊𝙉𝘼𝙍𝙍_𝙐𝙍𝙇: http://192.168.1.100:8989/sonarr/
✔ 𝘼𝙋𝙄_𝙆𝙀𝙔: xxxxxxxxxxx
✖️ Variabile d'ambinete '𝘾𝙃𝘼𝙏_𝙄𝘿' non inserita.
✖️ Variabile d'ambinete '𝘽𝙊𝙏_𝙏𝙊𝙆𝙀𝙉' non inserita.
☑️ Le variabili d'ambiente sono state inserite correttamente.
⚙️ Intervallo Scan: 30 minuti
AVVIO SERVER
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
╭-----------------------------------「18 Mar 2021 23:26:03」-----------------------------------╮
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
🔎 Ricerca anime 'My Hero Academia' per l'episodio S3E25.
🔎 Ricerca degli episodi per 'My Hero Academia'.
⚙️ Verifica se l'episodio 𝐒3𝐄25 è disponibile.
✔️ L'episodio è disponibile.
⏳ Download episodio 𝐒3𝐄25.
✔️ Dowload Completato.
⏳ Spostamento episodio 𝐒3𝐄25 in xxxxxxxxxxx/My Hero Academia.
⚠️ La cartella xxxxxxxxxxx/My Hero Academia è stata creata.
✔️ Episodio spostato.
⏳ Ricaricando la serie 'My Hero Academia'.
⏳ Rinominando l'episodio.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
╰-----------------------------------「18 Mar 2021 23:59:28」-----------------------------------╯
```

**Comment by MainKronos** [comment]
Il problema quindi è stato risolto? 😅

**Comment by EffeF** [comment]
Apparentemente si, adesso provo con altre serie...
