### ISSUE TITLE
ERROR - Auto ricerca

### ISSUE THREAD

**Issue by grievertime** [MainKronos/Sonarr-AnimeDownloader#47]
### Informazioni generali
* **Nome Anime**:  Ao-chan Can't Study!
* **Stagione**:  1

### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
⚠️ Ricerca automatica link di AnimeWorld per la 𝘴𝘵𝘢𝘨𝘪𝘰𝘯𝘦 1 della 𝘴𝘦𝘳𝘪𝘦 'Ao-chan Can't Study!'.
🅴🆁🆁🅾🆁: Errore al file table.json.
```
Traceback (most recent call last):
  File "/script/anime_downloader/functions.py", line 132, in converting
    link = linkSearch(anime["title"], season["num"], anime["tvdbID"])
  File "/script/anime_downloader/functions.py", line 59, in linkSearch
    result = bindAnime(title, int(season), tvdbID)
  File "/script/anime_downloader/functions.py", line 207, in bindAnime
    results = aw.find(anime_name)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 23, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 82, in find
    data = res.json()["animes"]
KeyError: 'animes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/script/anime_downloader/__init__.py", line 23, in job
    series = converting(raw_series)
  File "/script/anime_downloader/functions.py", line 142, in converting
    raise TableFormattingError
anime_downloader.exceptions.TableFormattingError: Errore al file table.json.
```

### Descrizione
L'errore sembra apparire solo quando l'auto-ricerca link è attiva (anche se in beta è veramente molto comoda). Una volta disabilitata l'auto ricerca link e riavviato il container tutto funziona correttamente.
L'auto ricerca funziona per alcuni anime, ma per quello in oggetto appare l'errore sopra citato.

**Comment by MainKronos** [comment]
Era un problema della libreria [animeworld](https://github.com/MainKronos/AnimeWorld-API)
Non capisco come mai utilizzando la funzione `aw.find('Ao-chan Can't Study!')` il server di AnimeWolrd restituisce errore.

In ogni caso dovrei aver sistemato, prova ad aggiornare la libreria interna al container Docker scrivendo questo comando come root: `pip install -U animeworld`

**Comment by MainKronos** [comment]
FIX con la versione [1.7.3](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.7.3)
