### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'connections/telegram.sh'

### ISSUE THREAD

**Issue by Simoneu01** [MainKronos/Sonarr-AnimeDownloader#64]
### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
```
🅴🆁🆁🅾🆁: [Errno 2] No such file or directory: 'connections/telegram.sh'
Traceback (most recent call last):
  File "/script/anime_downloader/__init__.py", line 84, in job
    message.warning(txt.CONNECTION_MESSAGE.format(title=anime["title"], season=episode["season"], episode=episode["num"], episodeTitle=episode["title"]))
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/script/logger.py", line 26, in emit
    subprocess.check_call([script, record.msg], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/local/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'connections/telegram.sh'
```

### Descrizione [_Opzionale_]
Non funziona telegram, forse qualche problema di permessi? cosa dovrebbe avere?

**Comment by MainKronos** [comment]
hai già messo i permessi di esecuzione (`chmod +x connections/telegram.sh`) ?

prova anche questo comando: 
```bash
sed -i -e 's/\r$//' connections/telegram.sh
```
