### ISSUE TITLE
[BUG] problema libreria animeworld

### ISSUE THREAD

**Issue by Simoneu01** [MainKronos/Sonarr-AnimeDownloader#85]
### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
```python
🅴🆁🆁🅾🆁: time data '??' does not match format '%d %B %Y'
Traceback (most recent call last):
  File "/script/job.py", line 32, in job
    series = fun.converting(raw_series)
  File "/script/utility/functions.py", line 144, in converting
    link = linkSearch(anime["title"], season["num"], anime["tvdbID"])
  File "/script/utility/functions.py", line 62, in linkSearch
    result = bindAnime(title, int(season), tvdbID)
  File "/script/utility/functions.py", line 221, in bindAnime
    results = aw.find(anime_name)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 60, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 55, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 120, in find
    return [
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 126, in <listcomp>
    "release": datetime.strptime(elem["release"], "%d %B %Y"),
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '??' does not match format '%d %B %Y'
```

### Informazioni generali
- **Nome Anime**: The Rising of the Shield Hero
- **Stagione**: 1

### Descrizione
Avvio il docker con installazione pulita, e mentre cerca gli anime da associare da questo errore.

**Comment by MainKronos** [comment]
Non riesco a replicare il problema, mi puoi inviare il log completo?
Premi il pulsante in fondo alla pagina del log e inviami il file. (Il file generato ha già offuscate le informazioni private)
![Immagine 2022-11-08 193338](https://user-images.githubusercontent.com/21228689/200647064-5cf1dc4f-d2fa-4532-8308-2421f7e16dea.png)

**Comment by Simoneu01** [comment]
Questo è il log completo:
[log.log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/9964751/log.log)

**Comment by MainKronos** [comment]
Ho rilasciato la nuova versione della libreria [animeworld](https://github.com/MainKronos/AnimeWorld-API/releases/tag/v1.4.22), riavvia il container e dovrebbe scomparire il problema

**Comment by Simoneu01** [comment]
Si quel problema è sparito, ora ho questo:
```
[4;3;91m🅴🆁🆁🅾🆁: '<' not supported between instances of 'NoneType' and 'datetime.datetime'[0m
Traceback (most recent call last):
  File "/script/job.py", line 32, in job
    series = fun.converting(raw_series)
  File "/script/utility/functions.py", line 144, in converting
    link = linkSearch(anime["title"], season["num"], anime["tvdbID"])
  File "/script/utility/functions.py", line 62, in linkSearch
    result = bindAnime(title, int(season), tvdbID)
  File "/script/utility/functions.py", line 238, in bindAnime
    ret.sort(key=lambda elem: elem["release"])
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```
[log (1).log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/9967956/log.1.log)

**Comment by MainKronos** [comment]
Prova la versione [dev](https://github.com/MainKronos/Sonarr-AnimeDownloader/pkgs/container/anime_downloader/49776097?tag=dev) e dimmi se il problema e stato risolto.

**Comment by Simoneu01** [comment]
> Prova la versione [dev](https://github.com/MainKronos/Sonarr-AnimeDownloader/pkgs/container/anime_downloader/49776097?tag=dev) e dimmi se il problema e stato risolto.

Si, con questo fix funziona! Ty!
